### ISSUE TITLE
Game.update() failure.

### ISSUE THREAD

**Issue by cscp** [itdelatrisu/opsu#264] opened 2017-03-04 16:34 UTC
**Version:** 0.15.0
**Build date:** 2017-02-05 00:04
**OS:** Windows 7 (x86)
**JRE:** 1.8.0_121
**OpenGL version:** 3.3.0 (NVIDIA Corporation)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:135)
	at itdelatrisu.opsu.Container.start(Container.java:79)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)
Caused by: java.lang.NullPointerException
	at itdelatrisu.opsu.audio.MusicController.setPitch(MusicController.java:447)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1592)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
```

What can i do now??

**Comment by tpenguinltg** [comment] 2017-03-04 17:14
Duplicate of #255. You can either wait for the next update or build from the latest commit.

**Closed** 2017-03-04 17:36 UTC
Labels: duplicate
