### ISSUE TITLE
Failed to load file '/preview/217134.mp3'.

### ISSUE THREAD

**Issue by SCNya** [itdelatrisu/opsu#84] opened 2015-05-14 18:26 UTC
**Version:** 0.8.0
**Build date:** 2015-03-20 04:45
**OS:** Linux (amd64)
**JRE:** 1.8.0_45-internal
**Error:** `Failed to load file '/preview/217134.mp3'.`
**Stack trace:**
```
java.lang.IllegalArgumentException: Invalid format
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.createStream(PulseAudioDataLine.java:142)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:99)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:283)
	at org.classpath.icedtea.pulseaudio.PulseAudioClip.open(PulseAudioClip.java:402)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:164)
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:94)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:118)
	at itdelatrisu.opsu.audio.SoundController.playTrack(SoundController.java:336)
	at itdelatrisu.opsu.states.DownloadsMenu$2.run(DownloadsMenu.java:488)
```

**Comment by SCNya** [comment] 2015-05-14 18:31
Need a start with "SUDO"

**Comment by itdelatrisu** [comment] 2015-05-14 19:13
I believe this is a duplicate of #59 - if so, a fix will be included in the next release.  Please let me know if you think it's a different problem.  Thanks!

**Closed by itdelatrisu** 2015-05-14 19:13 UTC

**Comment by SCNya** [comment] 2015-05-14 19:16
Thanks! <3
