### ISSUE TITLE
Failed to load audio file 'drum-hitclap.wav'.

### ISSUE THREAD

**Issue by casprussian** [itdelatrisu/opsu#284] opened 2017-04-12 23:00 UTC
**Version:** 0.15.0
**Build date:** 2017-02-05 00:04
**OS:** Linux (amd64)
**JRE:** 1.8.0_121
**OpenGL version:** 3.0 Mesa 8.0.5 (Tungsten Graphics, Inc)
**Error:** `Failed to load audio file 'drum-hitclap.wav'.`
**Stack trace:**
```
javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
	at com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:513)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.implOpen(DirectAudioDevice.java:1304)
	at com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:121)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1085)
	at com.sun.media.sound.DirectAudioDevice$DirectClip.open(DirectAudioDevice.java:1052)
	at itdelatrisu.opsu.audio.MultiClip.getClip(MultiClip.java:192)
	at itdelatrisu.opsu.audio.MultiClip.<init>(MultiClip.java:116)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:136)
	at itdelatrisu.opsu.audio.SoundController.loadClip(SoundController.java:99)
	at itdelatrisu.opsu.audio.SoundController.init(SoundController.java:251)
	at itdelatrisu.opsu.states.Splash$2.run(Splash.java:172)
```

**Comment by itdelatrisu** [comment] 2017-05-06 06:43
Thanks for reporting.  Seems like a duplicate of #267.

**Closed by itdelatrisu** 2017-05-06 06:43 UTC
