### ISSUE TITLE
Just letting you guys know, someone uploaded this to the Google Playstore.

### ISSUE THREAD

**Issue by MegaFish0527** [itdelatrisu/opsu#353] opened 2017-12-29 09:32 UTC
I don't think it was one of the devs here, so I'm just letting you guys know.

**Comment by Lyonlancer5** [comment] 2017-12-29 12:34
Duplicate of #346 
See [here](https://github.com/itdelatrisu/opsu/issues/346#issuecomment-350904627)

**Comment by itdelatrisu** [comment] 2017-12-29 18:28
Yup, this was reported earlier but thanks for the concern.

**Closed by itdelatrisu** 2017-12-29 18:28 UTC
