### ISSUE TITLE
**Uncaught Exeption** Only when a song is downloaded

### ISSUE THREAD

**Issue by TheCliptree** [itdelatrisu/opsu#173] opened 2016-01-11 14:30 UTC
Running windows 8
java.lang.UnsatisfiedLinkError: org.lwjgl.openal.AL10.nalGetSourcei(II)I
    at org.lwjgl.openal.AL10.nalGetSourcei(Native Method)
    at org.lwjgl.openal.AL10.alGetSourcei(AL10.java:853)
    at org.newdawn.slick.openal.SoundStore.isMusicPlaying(SoundStore.java:979)
    at org.newdawn.slick.Music.poll(Music.java:66)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:682)
    at itdelatrisu.opsu.Container.gameLoop(Container.java:98)
    at itdelatrisu.opsu.Container.start(Container.java:72)
    at itdelatrisu.opsu.Opsu.main(Opsu.java:205)

So i've downloaded opsu on my desktop running windows 10 and it works fine. But when I install opsu on my laptop it comes up with the error above. This error only happens when a song is in the song folder. When I delete the song from the song folder there is no problem.

**Comment by Lemmmy** [comment] 2016-01-11 17:50
Possible duplicate of #146.

**Closed** 2018-03-08 04:31 UTC
Labels: audio
