### ISSUE TITLE
Does opsu! uploaded to Google Play by original author??

### ISSUE THREAD

**Issue by AsrielTW** [itdelatrisu/opsu#343] opened 2017-12-09 09:44 UTC
https://imgur.com/gallery/xyHi4
I found it on Google Play

**Comment by Lemmmy** [comment] 2017-12-09 12:03
Duplicate of #340

**Comment by itdelatrisu** [comment] 2017-12-10 01:08
Not mine, but I don't care.

**Closed by itdelatrisu** 2017-12-10 01:08 UTC
