### ISSUE TITLE
Failed to create JSON object.

### ISSUE THREAD

**Issue by zProx** [itdelatrisu/opsu#141] opened 2015-10-02 00:44 UTC
**Version:** 0.12.0
**Build date:** 2015-09-22 06:40
**OS:** Windows 7 (amd64)
**JRE:** 1.8.0_60
**Error:** `Failed to create JSON object.`
**Stack trace:**
```
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at itdelatrisu.opsu.Utils.readJsonObjectFromUrl(Utils.java:411)
	at itdelatrisu.opsu.downloads.servers.BloodcatServer.resultList(BloodcatServer.java:71)
	at itdelatrisu.opsu.states.DownloadsMenu$SearchQuery.run(DownloadsMenu.java:213)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by itdelatrisu** [comment] 2015-10-02 03:11
Duplicate of #139.  Fixed in the 0.12.1 release.  Thanks for reporting!

**Closed by itdelatrisu** 2015-10-02 03:11 UTC
