### ISSUE TITLE
Game.update() failure.

### ISSUE THREAD

**Issue by casprussian** [itdelatrisu/opsu#285] opened 2017-04-12 23:04 UTC
**Version:** 0.15.0
**Build date:** 2017-02-05 00:04
**OS:** Linux (amd64)
**JRE:** 1.8.0_121
**OpenGL version:** 3.0 Mesa 8.0.5 (Tungsten Graphics, Inc)
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.update() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:708)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:135)
	at itdelatrisu.opsu.Container.start(Container.java:79)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:216)
Caused by: java.lang.NullPointerException
	at itdelatrisu.opsu.audio.MusicController.setPitch(MusicController.java:447)
	at itdelatrisu.opsu.states.Game.enter(Game.java:1592)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:248)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:702)
	... 3 more
```

**Comment by tpenguinltg** [comment] 2017-04-13 02:30
Looks like a duplicate of #255. This is already fixed in master and will be fixed in the next release.

**Closed** 2017-04-13 04:09 UTC
