### ISSUE TITLE
Game.render() failure.

### ISSUE THREAD

**Issue by SolarAquarion** [itdelatrisu/opsu#98] opened 2015-06-21 23:40 UTC
**Version:** 0.9.0
**Build date:** 2015-06-21 23:27
**OS:** Linux (amd64)
**JRE:** 1.8.0_45
**Stack trace:**
```
org.newdawn.slick.SlickException: Game.render() failure.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:730)
	at itdelatrisu.opsu.Container.gameLoop(Container.java:96)
	at itdelatrisu.opsu.Container.start(Container.java:70)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:169)
Caused by: java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL32.glFramebufferTexture(GL32.java:389)
	at itdelatrisu.opsu.render.Rendertarget.createRTTFramebuffer(Rendertarget.java:107)
	at itdelatrisu.opsu.render.FrameBufferCache.insert(FrameBufferCache.java:119)
	at itdelatrisu.opsu.render.CurveRenderState.draw(CurveRenderState.java:104)
	at itdelatrisu.opsu.objects.curves.Curve.draw(Curve.java:125)
	at itdelatrisu.opsu.objects.Slider.draw(Slider.java:181)
	at itdelatrisu.opsu.states.Game.drawHitObjects(Game.java:1258)
	at itdelatrisu.opsu.states.Game.render(Game.java:515)
	at org.newdawn.slick.state.StateBasedGame.render(StateBasedGame.java:199)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:727)
	... 3 more
```

**Comment by wacossusca34** [comment] 2015-06-21 23:52
You need to install a graphics driver that fully supports FBOs (framebuffers). What driver and graphics card (or chip) are you using?

**Comment by SolarAquarion** [comment] 2015-06-21 23:53
So basically primus?

**Comment by wacossusca34** [comment] 2015-06-22 00:32
primus is not a graphics driver (it is a shared library). You need libraries and/or drivers (depending on the dependencies for your graphics driver) that allow you to use framebuffers in accelerated applications. Both the open source and properietary drivers for Nvidia and AMD graphics cards support these, and Intel's official, open source drivers for their integrated chipsets should also work.

It would help if you provided more information about the driver(s) you are currently using and your hardware :)

**Comment by SolarAquarion** [comment] 2015-06-22 00:33
I decided to open opsu without enabling nvidia

**Comment by wacossusca34** [comment] 2015-06-22 00:34
That would probably be why it's not working, haha

**Comment by itdelatrisu** [comment] 2015-06-22 02:33
I added more checks before attempting to use the new slider style.  Does 392df79 fix the issue?

**Comment by itdelatrisu** [comment] 2015-08-08 18:10
Closing for now, please re-open if the issue isn't resolved.

**Closed by itdelatrisu** 2015-08-08 18:10 UTC
Labels: bug
