### ISSUE TITLE
** Uncaught Exception! ** Error

### ISSUE THREAD

**Issue by Zero87879** [itdelatrisu/opsu#206] opened 2016-12-04 13:03 UTC
So i was about to launch the .jar file of Opsu,and i got this error.
Can you please help me escape this ERROR?
**Version:** 0.12.1
**Build date:** 2015-10-02 03:05
**OS:** Windows 7 (amd64)
**JRE:** 1.8.0_101
**Error:** `** Uncaught Exception! **`
**Stack trace:**
```
java.lang.NullPointerException
	at itdelatrisu.opsu.GameImage.setDefaultImage(GameImage.java:630)
	at itdelatrisu.opsu.GameImage.getImage(GameImage.java:568)
	at itdelatrisu.opsu.ui.Cursor.reset(Cursor.java:284)
	at itdelatrisu.opsu.Container.close_sub(Container.java:121)
	at itdelatrisu.opsu.Container.start(Container.java:75)
	at itdelatrisu.opsu.Opsu.main(Opsu.java:205)
```

**Comment by Lemmmy** [comment] 2016-12-05 09:51
Duplicate of #135, #185, #193, #195, #200 and #204.
Please provide more information.

Are you using a skin?
Where is your game saved to?
What graphics driver are you using?

**Comment by Zero87879** [comment] 2016-12-05 18:56
"Are you using a skin?" No.
"Where is your game saved to?" I havent even played it yet.
"What graphices driver are you using?" ATI Radeon 4800 Series HD

2016-12-05 10:51 GMT+01:00 DDDDDDDDDdfsasdsafsd <notifications@github.com>:

**Comment by Lemmmy** [comment] 2016-12-05 19:05
By "Where is your game saved to?" I meant where did you install the game? The full path, please. E.g. `C:/Users/Zero87879/Games/opsu!`

**Comment by Zero87879** [comment] 2016-12-08 07:54
Full path of where its installed to..
Well.i keep it in my "Downloads" folder,the JAR file.
So its in my downloads. should i extract anywhere?

2016-12-05 20:05 GMT+01:00 DDDDDDDDDdfsasdsafsd <notifications@github.com>:

**Comment by Lemmmy** [comment] 2016-12-08 16:59
Can you post your `.opsu.log` file please? From what I can tell, getSkin() is returning null (which is apparently expected behaviour?) when the images are being loaded. So for some reason, the default skin is not being loaded.

**Comment by Lemmmy** [comment] 2016-12-08 17:01
Additionally, I asked for the full path. This will usually look something like `C:/Users/Zero87879/Games/opsu`. You can find it by looking at the top bar (address bar) of Windows Explorer.

**Comment by Lemmmy** [comment] 2016-12-10 18:57
@Zero87879 where did you download the opsu! jar from?

**Comment by itdelatrisu** [comment] 2016-12-20 20:27
Cleaning out old issues related to #218, please open another issue if this happens again. Thanks!

**Closed by itdelatrisu** 2016-12-20 20:27 UTC

**Comment by Zero87879** [comment] 2016-12-22 10:52
The official GitHub download. Thats where.

2016-12-10 19:57 GMT+01:00 DDDDDDDDDdfsasdsafsd <notifications@github.com>:

**Comment by Zero87879** [comment] 2016-12-22 10:52
C:/Users/Zee/Downloads/opsu is the fullpath. It may be wrong,but it seems
that this is the right path.

2016-12-08 18:01 GMT+01:00 DDDDDDDDDdfsasdsafsd <notifications@github.com>:

**Comment by Zero87879** [comment] 2016-12-22 10:54
.Opsu.log? Sure.


2016-12-08 17:59 GMT+01:00 DDDDDDDDDdfsasdsafsd <notifications@github.com>:
